parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  sourceType: module
env:
  es6: true
  browser: true
  commonjs: true
plugins:
  - 'eslint-plugin-vue'
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - 'plugin:vue/base'
  - 'plugin:vue/strongly-recommended'
rules:
  strict:
    - 0
  indent:
    - 2
    - 4
    -
      SwitchCase: 1
  radix:
    - 2
    - always
  comma-spacing:
    - 2
    -
      before: false
      after: true
  no-multiple-empty-lines:
    - 2
  object-curly-spacing:
    - 2
    -
      anoymous: always
      named: never
      asyncArrow: always
  space-in-parens:
    - 2
